trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x.x'

- script: dotnet restore
  displayName: Restore

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build

- script: dotnet test --collect:"Code Coverage"
  displayName: Test

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudConnection'
    organization: 'myorg'
    scannerMode: 'MSBuild'
    projectKey: 'dotnet-webapp'
    projectName: 'DotNet Web App'

- script: dotnet build
  displayName: 'Run SonarQube Analysis'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
